// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmvgx-ACPgHy0FdWgpX31aFcPS_fW_DeE',
    appId: '1:615868022923:web:b67f193bf2ee7c6f40d48e',
    messagingSenderId: '615868022923',
    projectId: 'venom-todo-app',
    authDomain: 'venom-todo-app.firebaseapp.com',
    storageBucket: 'venom-todo-app.appspot.com',
    measurementId: 'G-TSGH2ZGBZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3f6mNUhT1dbAxiFROw2_5X38nyLmzpxQ',
    appId: '1:615868022923:android:9041733460e7c15b40d48e',
    messagingSenderId: '615868022923',
    projectId: 'venom-todo-app',
    storageBucket: 'venom-todo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmg4LSMqdj3SO0JdyUqxGSs0hCy9SWr4M',
    appId: '1:615868022923:ios:e8fb83c04ae94fb840d48e',
    messagingSenderId: '615868022923',
    projectId: 'venom-todo-app',
    storageBucket: 'venom-todo-app.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmg4LSMqdj3SO0JdyUqxGSs0hCy9SWr4M',
    appId: '1:615868022923:ios:52d0791f95b7a72940d48e',
    messagingSenderId: '615868022923',
    projectId: 'venom-todo-app',
    storageBucket: 'venom-todo-app.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
